// vue/src/components/DokaObject.vue
<template>
  <div class="flex items-start space-x-6 p-6 bg-green-100 rounded-lg shadow-md">
    <!-- Properties List -->
    <div class="flex-1 bg-blue-100 p-4 rounded-lg shadow">
      <h2 class="text-lg font-semibold text-gray-700 mb-4">Properties</h2>
      <ul class="space-y-2">
        <li v-for="(property, index) in props.properties" :key="index" class="text-gray-600">
          <span class="font-semibold">{{ property.key }}:</span> {{ property.value }}
        </li>
      </ul>
    </div>

    <!-- Image Preview -->
    <div
        v-if="props.binaryFile"
        class="flex-1 flex items-center justify-center bg-yellow-100 p-4 rounded-lg shadow w-96 h-96 "
    >
      <img :src="imageUrl" alt="Uploaded" class="h-full w-full object-contain rounded" />
    </div>
    <div v-else class="flex-1 flex items-center justify-center bg-yellow-100 p-4 rounded-lg shadow h-64 w-64">
      <p class="text-gray-500">No image available</p>
    </div>
  </div>
</template>

<script lang="ts" setup>
import {ref, watch} from 'vue'

interface Property {
  key: string;
  value: string;
}

interface Props {
  properties: Property[]
  binaryFile?: File
}

const props = defineProps<Props>()

const imageUrl = ref<string | undefined>(undefined)


// Convert binary file to a data URL
const loadImage = (file: File) => {
  const reader = new FileReader();
  reader.onload = () => {
    imageUrl.value = reader.result as string;
  }
  reader.readAsDataURL(file)
}

watch(() => props.binaryFile, (newFile) => {
  if (newFile) {
    loadImage(newFile)
  }
}, { immediate: true })
</script>

<style scoped>

</style>

// svelte/src/lib/DokaObject.svelte
<script lang="ts">
    export let binaryFile: File | undefined;
    export let properties: { key: string; value: string }[] = [];

    let imageUrl: string | undefined = undefined;

    // Reactive statement to update the image URL when binaryFile changes
    $: if (binaryFile) {
        const reader = new FileReader();
        reader.onload = () => {
            imageUrl = reader.result as string;
        };
        reader.readAsDataURL(binaryFile);
    } else {
        imageUrl = undefined;
    }
</script>

<div class="doka-object border p-4 rounded shadow">
    {#if imageUrl}
        <img src={imageUrl} alt="Doka Object" class="w-full h-auto" />
    {:else}
        <div class="placeholder bg-gray-200 p-4 text-center">No image available</div>
    {/if}

    {#if properties.length > 0}
        <ul class="mt-2">
            {#each properties as prop}
                <li><strong>{prop.key}:</strong> {prop.value}</li>
            {/each}
        </ul>
    {/if}
</div>

<style>
    .doka-object {
        font-family: sans-serif;
        background-color: #fff;
    }
    .placeholder {
        font-size: 0.9rem;
        color: #666;
    }
</style>
